"""Lockfile type detection (filename first, then light content sniffing)."""
from __future__ import annotations

import json
import re
from typing import Any

from ..models import Ecosystem
from ..security import escape_controls, redact_secrets
from .base import MAX_FIELD_LEN, LockfileParseError, ParsedLockfile, UnsupportedLockfile, to_text
from .golang import parse_go_mod, parse_go_sum
from .npm import parse_package_lock, parse_yarn_lock
from .pylock import parse_poetry_lock, parse_uv_lock
from .pypi import parse_pipfile_lock, parse_pyproject, parse_requirements
from .rust import parse_cargo_lock

SUPPORTED_KINDS = [
    "package-lock.json", "yarn.lock", "requirements.txt", "Pipfile.lock", "pyproject.toml", "poetry.lock", "uv.lock",
    "go.mod", "go.sum", "Cargo.lock",
]

# Lockfiles of other package managers: recognised so the error can say *why* the file is not analysed.
KNOWN_UNSUPPORTED = {
    "pnpm-lock.yaml": "pnpm-lock.yaml (pnpm) is not supported yet - scan the project's package-lock.json or yarn.lock instead.",
    "bun.lockb": "bun.lockb (Bun) is a binary lockfile and is not supported - run `bun install --save-text-lockfile` "
                 "or scan package-lock.json.",
    "bun.lock": "bun.lock (Bun) is not supported yet - scan package-lock.json or yarn.lock instead.",
    "composer.lock": "composer.lock (PHP/Packagist) is not supported; RIPPLE covers npm, PyPI, Go and crates.io.",
    "gemfile.lock": "Gemfile.lock (RubyGems) is not supported; RIPPLE covers npm, PyPI, Go and crates.io.",
    "pubspec.lock": "pubspec.lock (Dart/pub) is not supported; RIPPLE covers npm, PyPI, Go and crates.io.",
    "packages.lock.json": "packages.lock.json (NuGet) is not supported; RIPPLE covers npm, PyPI, Go and crates.io.",
    "pom.xml": "pom.xml (Maven) is not supported; RIPPLE covers npm, PyPI, Go and crates.io.",
    "package.json": "package.json declares ranges only - scan the matching package-lock.json or yarn.lock instead.",
    "environment.yml": "environment.yml (conda) is not supported; export a requirements.txt with `pip freeze`.",
    "pdm.lock": "pdm.lock is not supported yet - export with `pdm export -f requirements` and scan the requirements file.",
}


def _basename(filename: str) -> str:
    return filename.replace("\\", "/").rsplit("/", 1)[-1].strip()


def detect_kind(filename: str, content: bytes | str | None = None) -> str | None:
    low = _basename(filename).lower()
    if low in ("package-lock.json", "npm-shrinkwrap.json"):
        return "package-lock.json"
    if low == "yarn.lock":
        return "yarn.lock"
    if low == "pipfile.lock":
        return "Pipfile.lock"
    if low == "pyproject.toml":
        return "pyproject.toml"
    if low == "poetry.lock":
        return "poetry.lock"
    if low == "uv.lock":
        return "uv.lock"
    if low == "go.mod":
        return "go.mod"
    if low == "go.sum":
        return "go.sum"
    if low == "cargo.lock":
        return "Cargo.lock"
    if re.match(r"^(requirements|constraints)[\w.-]*\.(txt|in)$", low) or (
            low.endswith(".txt") and low.startswith(("req", "dev-req", "prod-req"))):
        return "requirements.txt"
    parent = filename.replace("\\", "/").rsplit("/", 2)[-2].lower() if filename.replace("\\", "/").count("/") else ""
    if parent in ("requirements", "reqs") and low.endswith((".txt", ".in")):
        return "requirements.txt"
    if content is None:
        return None
    try:
        text = to_text(content).lstrip()
    except LockfileParseError:
        return None
    if text.startswith("{"):
        try:
            data: Any = json.loads(text)
        except (ValueError, RecursionError):
            return None
        if isinstance(data, dict):
            if "lockfileVersion" in data and ("packages" in data or "dependencies" in data):
                return "package-lock.json"
            if "_meta" in data and ("default" in data or "develop" in data):
                return "Pipfile.lock"
        return None
    if "# yarn lockfile v1" in text[:200] or "__metadata:" in text[:400]:
        return "yarn.lock"
    if text.startswith("# This file is automatically @generated by Cargo") or (
            re.search(r"^\[\[package\]\]", text, re.M) and "checksum" in text):
        return "Cargo.lock"
    if re.match(r"^\s*module\s+\S+", text) and re.search(r"^\s*(go|require)\b", text, re.M):
        return "go.mod"
    return None


_PARSERS = {
    "package-lock.json": parse_package_lock, "yarn.lock": parse_yarn_lock, "requirements.txt": parse_requirements,
    "Pipfile.lock": parse_pipfile_lock, "pyproject.toml": parse_pyproject, "poetry.lock": parse_poetry_lock,
    "uv.lock": parse_uv_lock, "go.mod": parse_go_mod,
    "go.sum": parse_go_sum, "Cargo.lock": parse_cargo_lock,
}

_ECO_DEFAULT_KIND = {
    Ecosystem.PYPI: "requirements.txt", Ecosystem.NPM: "package-lock.json",
    Ecosystem.GO: "go.mod", Ecosystem.RUST: "Cargo.lock",
}


def _scrub(parsed: ParsedLockfile) -> ParsedLockfile:
    """Mask credentials in every URL-ish string a parser collected (they end up in evidence and reports)."""
    for attr in ("index_urls", "extra_index_urls", "insecure_sources", "includes", "warnings"):
        setattr(parsed, attr, [redact_secrets(escape_controls(v))[:MAX_FIELD_LEN] for v in getattr(parsed, attr)])
    for pkg in parsed.packages:      # parsers also assign registry_source/spec after construction (e.g. the primary index)
        for attr in ("registry_source", "spec"):
            val = getattr(pkg, attr)
            if isinstance(val, str) and "@" in val:
                setattr(pkg, attr, redact_secrets(val))
    for key, val in list(parsed.meta.items()):
        if isinstance(val, list):
            parsed.meta[key] = [redact_secrets(escape_controls(v))[:MAX_FIELD_LEN] if isinstance(v, str) else v for v in val]
    return parsed


def parse_file(filename: str, content: bytes | str, ecosystem: Ecosystem | str | None = None) -> ParsedLockfile:
    """Parse one manifest/lockfile. ``ecosystem`` forces a parser for files whose name is not recognised."""
    kind = detect_kind(filename, content)
    if kind is None and ecosystem is not None:
        kind = _ECO_DEFAULT_KIND[Ecosystem(ecosystem)]
    if kind is None:
        hint = KNOWN_UNSUPPORTED.get(_basename(filename).lower())
        raise UnsupportedLockfile(
            hint or f"'{_basename(filename)}' is not a supported file. Supported: " + ", ".join(SUPPORTED_KINDS) + ".", filename)
    try:
        return _scrub(_PARSERS[kind](content, filename))
    except LockfileParseError:
        raise
    except (RecursionError, MemoryError) as exc:
        raise LockfileParseError("The file is nested too deeply or is too large to analyse.", filename) from exc
    except Exception as exc:  # noqa: BLE001 - hostile/odd structure (wrong types, missing keys): a friendly error, never a crash
        raise LockfileParseError(
            f"The structure of this {kind} file is not what a valid lockfile contains.", filename) from exc


def detect_file(filename: str, content: bytes | str, ecosystem: Ecosystem | str | None = None) -> dict[str, Any]:
    """Cheap detection result for the UI: ``{filename, ecosystem, supported, kind, dependency_count, error}``."""
    base: dict[str, Any] = {"filename": filename, "ecosystem": None, "supported": False, "kind": None,
                            "dependency_count": 0, "error": None}
    try:
        parsed = parse_file(filename, content, ecosystem)
    except UnsupportedLockfile as e:
        base["error"] = e.message
        return base
    except LockfileParseError as e:
        base["kind"] = detect_kind(filename, content) or (_ECO_DEFAULT_KIND[Ecosystem(ecosystem)] if ecosystem else None)
        base["error"] = e.message
        return base
    except Exception:  # noqa: BLE001 - never leak internals
        base["error"] = "The file could not be parsed."
        return base
    base.update(ecosystem=parsed.ecosystem.value, supported=True, kind=parsed.kind,
                dependency_count=len(parsed.packages))
    return base
